apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempconverter
  namespace: tempconverter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tempconverter
  template:
    metadata:
      labels:
        app: tempconverter
    spec:
      containers:
        - name: tempconverter
          image: docker.io/madjyx/tempconverter:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-pass
            - name: DB_HOST
              value: "mysql"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-name
            - name: STUDENT
              value: "Zvonimir TvojePrezime"
            - name: COLLEGE
              value: "Algebra Bernays University"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
