apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: tempconverter
type: Opaque
stringData:
  db-user: appuser
  db-pass: apppassword
  db-name: tempconverter
  mysql-root-password: rootpassword
